### ISSUE TITLE
スラッシュが二重になるのをなんとかしたい (dotfiles_dotfiles.src_dir 省略時)

### ISSUE THREAD

**Issue by ryunix** [ryunix/ansible-role-dotfiles#2]
現状は以下の通り。
動作に影響がないのは分かってるけど、きもちわるい...

```yaml
---
- hosts: all
  gather_facts: no
  roles:
    - role: dotfiles
      dotfiles_repo: https://github.com/ryunix/dotfiles
      dotfiles_dest: ~/.dotfiles
      dotfiles_version: my-dotfiles
      dotfiles_dotfiles:
        - { src: .gitconfig, dest_dir: "~" }
        - { src_dir: .atom, src: config.cson, dest_dir: ~/.atom }
```

```console
lrwxr-xr-x  1 ryunix  staff  35  7 26 16:24 .gitconfig -> /Users/ryunix/.dotfiles//.gitconfig
lrwxr-xr-x  1 ryunix  staff  41  7 26 16:24 .atom/config.cson -> /Users/ryunix/.dotfiles/.atom/config.cson
```
